import Link from 'next/link';
import ProductVisual from '@/components/ProductVisual';
import { products } from '@/lib/products';

export default function Home() {
  const featured = products.filter((p) => p.badge || ['Bebidas','Cuidado facial'].includes(p.category)).slice(0, 6);
  return <main>
    <div style={{background:'var(--deep)',color:'white',padding:'9px',textAlign:'center',fontSize:13}}>Envíos disponibles en Ecuador · Atención personalizada por WhatsApp</div>
    <header style={{background:'white',borderBottom:'1px solid #e5e5e5',position:'sticky',top:0,zIndex:10}}><div className="container" style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'18px 0'}}><div><strong style={{fontSize:25,color:'var(--deep)',fontFamily:'Georgia'}}>Aloe & Bienestar</strong><div style={{fontSize:10,letterSpacing:2,color:'var(--green)'}}>NUTRICIÓN · BELLEZA · BIENESTAR</div></div><nav style={{display:'flex',gap:25,fontSize:14}}><Link href="/productos">Productos</Link><a href="#nosotros">Nosotros</a><a href="#contacto">Contacto</a><Link href="/carrito">🛒 Carrito</Link></nav></div></header>
    <section style={{background:'var(--pale)',padding:'78px 0'}}><div className="container" style={{display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:50,alignItems:'center'}}><div><div style={{color:'var(--green)',fontWeight:700,letterSpacing:2,fontSize:13}}>BIENESTAR QUE SE SIENTE</div><h1 style={{fontFamily:'Georgia',fontSize:'clamp(42px,6vw,70px)',lineHeight:1.03,color:'var(--deep)',margin:'15px 0'}}>Tu mejor versión empieza hoy.</h1><p style={{fontSize:18,lineHeight:1.7,maxWidth:600}}>Ahora puedes explorar el catálogo Ecuador 2026 de Aloe & Bienestar, consultar cada producto y comprar en línea.</p><div style={{display:'flex',gap:14,marginTop:28}}><Link href="/productos" style={{background:'var(--deep)',color:'white',padding:'15px 25px',borderRadius:30,fontWeight:700}}>Ver catálogo</Link><a href="#contacto" style={{border:'1px solid var(--green)',color:'var(--deep)',padding:'15px 25px',borderRadius:30,fontWeight:700}}>Quiero asesoría</a></div></div><div style={{minHeight:340,borderRadius:35,background:'linear-gradient(145deg,#A8CDB8,#EAF5EE)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:110}}>🌿</div></div></section>
    <section className="container" style={{padding:'28px 0',display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:15}}>{[['🚚','Envíos en Ecuador'],['🔒','Compra segura'],['💳','Pago con tarjeta']].map(([i,t])=><div key={t} style={{background:'white',padding:20,borderRadius:15,textAlign:'center'}}><div style={{fontSize:25}}>{i}</div><strong>{t}</strong></div>)}</section>
    <section id="productos" className="container" style={{padding:'65px 0'}}><div style={{textAlign:'center'}}><div style={{color:'var(--green)',fontWeight:700}}>CATÁLOGO ECUADOR 2026</div><h2 style={{fontFamily:'Georgia',fontSize:42,color:'var(--deep)',margin:'10px 0 35px'}}>Productos destacados</h2></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{featured.map(p=><article key={p.id} style={{background:'white',borderRadius:20,overflow:'hidden',boxShadow:'0 8px 30px #0f513814'}}><Link href={'/producto/' + p.slug}><ProductVisual src={p.image} name={p.name} className="h-56" /></Link><div style={{padding:22}}><small style={{color:'var(--green)',fontWeight:700}}>{p.category}</small><Link href={'/producto/' + p.slug}><h3 style={{fontSize:20}}>{p.name}</h3></Link><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong style={{color:'var(--deep)',fontSize:20}}>${p.price.toFixed(2)}</strong><Link href={'/producto/' + p.slug} style={{background:'var(--deep)',color:'white',borderRadius:25,padding:'10px 16px'}}>Ver producto</Link></div></div></article>)}</div><div style={{textAlign:'center',marginTop:35}}><Link href="/productos" style={{fontWeight:700,color:'var(--green)'}}>Ver catálogo completo →</Link></div></section>
    <section id="nosotros" style={{background:'var(--deep)',color:'white',padding:'65px 0'}}><div className="container" style={{textAlign:'center'}}><h2 style={{fontFamily:'Georgia',fontSize:40}}>Tu bienestar, nuestra prioridad.</h2><p style={{maxWidth:700,margin:'auto',lineHeight:1.8,opacity:.9}}>Compra en línea de forma sencilla, revisa la ficha del producto y elige entre carrito, pago online o atención personalizada por WhatsApp.</p></div></section>
    <footer id="contacto" style={{background:'#092f22',color:'white',padding:'35px 0'}}><div className="container" style={{display:'flex',justifyContent:'space-between'}}><span>© {new Date().getFullYear()} Aloe & Bienestar</span><Link href="/carrito">🛒 Ir al carrito</Link></div></footer>
  </main>;
}